import { GetStaticProps } from 'next';
import SkillPage from '../components/pages/SkillPage';
import { passThroughProps } from '../utils/passThroughProps';

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      treemaps: [
        {
          data: {
            type: 'treemap',
            labels: [
              'Front-end',
              'HTML',
              'HTML5',
              'Semactic HTML',
              'CSS',
              'CSS3',
              'Transform',
              'Transition',
              'Grid',
              'Flex Box',
              'Responsive Web',
              'CSS Preprocessor',
              'Sass',
              'Modern CSS',
              'BEM',
              'CSS Modules',
              'Scoped CSS',
              'JavaScript',
              'ES6',
              'TypeScript',
              'Task Runner',
              'npm scripts',
              'gulp',
              'Testing',
              'Jest',
              'Cypress',
              'Bundler',
              'webpack',
              'rollup',
              'Linter',
              'eslint',
              'Prettier',
              'Version Control System',
              'Git',
              'GitHub',
              'GitLab',
              'Package Manager',
              'npm',
              'JS Framework',
              'React',
              'Vue',
              'Preact',
              'Svetle',
              'CSS Framework',
              'Material UI',
              'Web Components',
              'Customized built-in elements',
              'Server Side Rendering',
              'GatsbyJS',
              'Next.js',
              'State Management',
              'Redux',
              'Vuex',
              'Web',
              'Storage',
              'WebRTC',
              'Web Socket',
              'Device Orientation',
              'Location',
              'Service Worker',
              'Web Worker',
              'Mobile Application',
              'Ionic',
              'Flutter',
            ],
            parents: [
              '',
              'Front-end',
              'HTML',
              'HTML',
              'Front-end',
              'CSS',
              'CSS3',
              'CSS3',
              'CSS3',
              'CSS3',
              'CSS',
              'Front-end',
              'CSS Preprocessor',
              'Front-end',
              'Modern CSS',
              'Modern CSS',
              'Modern CSS',
              'Front-end',
              'JavaScript',
              'JavaScript',
              'JavaScript',
              'Task Runner',
              'Task Runner',
              'JavaScript',
              'Testing',
              'Testing',
              'JavaScript',
              'Bundler',
              'Bundler',
              'JavaScript',
              'Linter',
              'Linter',
              'Front-end',
              'Version Control System',
              'Version Control System',
              'Version Control System',
              'Front-end',
              'Package Manager',
              'Front-end',
              'JS Framework',
              'JS Framework',
              'JS Framework',
              'JS Framework',
              'Front-end',
              'CSS Framework',
              'Front-end',
              'Web Components',
              'Front-end',
              'Server Side Rendering',
              'Server Side Rendering',
              'Front-end',
              'State Management',
              'State Management',
              'Front-end',
              'Web',
              'Web',
              'Web',
              'Web',
              'Web',
              'Web',
              'Web',
              'Front-end',
              'Mobile Application',
              'Mobile Application',
              '',
            ],
          },
          colorway: [
            '#ffeb3b',
            '#03a9f4',
            '#3f51b5',
            '#ff9800',
            '#2196f3',
            '#f44336',
            '#ff5722',
            '#ffc107',
            '#673ab7',
            '#009688',
            '#e91e63',
            '#f44336',
            '#2196f3',
            '#ff5722',
          ],
        },
        {
          data: {
            type: 'treemap',
            labels: [
              'Backend',
              'Node.js',
              'Framework',
              'Express',
              'Testing',
              'Jest',
              'RESTful APIs',
              'Authentication',
              'JSON Web Token',
              'Docker',
              'Storage',
              'Relational Databases',
              'MySQL',
              'NoSQL Databases',
              'MongoDB',
            ],
            parents: [
              '',
              'Backend',
              'Node.js',
              'Framework',
              'Node.js',
              'Testing',
              'Backend',
              'Backend',
              'Authentication',
              'Backend',
              'Backend',
              'Storage',
              'Relational Databases',
              'Storage',
              'NoSQL Databases',
            ],
          },
          colorway: ['#8bc34a', '#ff9800', '#673ab7', '#3f51b5', '#2196f3'],
        },
        {
          data: {
            type: 'treemap',
            labels: [
              'DevOps',
              'Operation System',
              'Linux',
              'Mac OS',
              'Window',
              'Cloud',
              'Heroku',
              'AWS',
              'AWS Lambda',
              'CI / CD',
              'Travis',
            ],
            parents: [
              '',
              'DevOps',
              'Operation System',
              'Operation System',
              'Operation System',
              'DevOps',
              'Cloud',
              'Cloud',
              'AWS',
              'DevOps',
              'CI / CD',
            ],
          },
          colorway: ['#607d8b', '#9e9e9e', '#795548'],
        },
        {
          data: {
            type: 'treemap',
            labels: ['Learning', 'Machine Learning', 'Golang', 'Python', 'Kubernetes'],
            parents: ['', 'Learning', 'Learning', 'Learning', 'Learning'],
          },
          colorway: ['#ff9800', '#03a9f4', '#ffeb3b', '#3f51b5'],
        },
      ],
    },
  };
};

export default passThroughProps(SkillPage);
